### ISSUE TITLE
Equiv of ldrb.fiber_to_xdmf in fenicsx-ldrb?

### ISSUE THREAD

**Issue by AnoopRKulkarni** [finsberg/fenicsx-ldrb#19]
What is the equivalent of 

`ldrb.fiber_to_xdmf(fiber, "fiber")
`
in fenicsx-ldrb?

Thanks!

**Comment by finsberg** [comment]
Hi @AnoopRKulkarni. Thanks for bringing this up. This is not something I have implemented yet.

If you are looking for a way to color the arrows based on the angles then please check out my comment in https://github.com/finsberg/ldrb/issues/59#issuecomment-2274289782

If you want to visualize quadrature functions, then I plan to implement some support for this using the gist [here](https://gist.github.com/jorgensd/6b3db748009ac1017929d7e7f3e83dc2) as starting point. I think though, that it might be better to make a separate package for this, because this might be useful in other projects as well. 

If you don't work with quadrature functions then I think it should be possible to save the function in vtx format, see e.g https://github.com/finsberg/fenicsx-ldrb/blob/90a16b1ebe27dac1f0427757cfac969467958f6b/src/ldrb/cli.py#L144

**Comment by AnoopRKulkarni** [comment]
Thank you! I as much thought so. Thanks for all the supported links.

For now, I solved my problem by using dolfinx.io.VTXFilter and saving as *.bp and then my custom converters to convert them to my format (XDMF happened to be one of them but primarily openCARP).

Thanks again
~anoop
